export const SUITECUT_EVENT_ATTACHMENT = 'suitecut-events.json' as const
export const SUITECUT_MANIFEST_SCHEMA_VERSION = 1 as const

export const DEFAULT_SUITE_CUT_ZOOM_SCALE = 1.15
export const MAX_SUITE_CUT_ZOOM_SCALE = 1.25
export const DEFAULT_SUITE_CUT_ZOOM_PADDING_PX = 24
export const DEFAULT_SUITE_CUT_ZOOM_ENTER_DURATION_MS = 260
export const DEFAULT_SUITE_CUT_ZOOM_HOLD_MS = 900
export const DEFAULT_SUITE_CUT_ZOOM_EXIT_DURATION_MS = 220
